-- CSV種類マスタ（アップロード取り込み/CSV実績ファイル出力専用）
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${csvno.item}',     1, 0, 'ITEM',   '商品マスタ',      0, 1);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${csvno.chute}',    2, 0, 'CHUTE',  'シュートマスタ',  0, 1);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${csvno.shop}',     3, 0, 'SHOP',   '店舗マスタ',      0, 1);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${csvno.task}',     4, 0, 'TASK',   '作業指示データ',  0, 1);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${csvno.result}',   5, 0, 'RESULT', 'CSV実績ファイル', 0, 1);
-- CSV種類マスタ（インポート/エクスポート専用）
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-item}',           101, 1, 'RESULT_ITEM',          '商品マスタテーブル（インポート/エクスポート専用）',           1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-chute}',          102, 1, 'RESULT_CHUTE',         'シュートマスタテーブル（インポート/エクスポート専用）',       1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-shop}',           103, 1, 'RESULT_SHOP',          '店舗マスタテーブル（インポート/エクスポート専用）',           1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-batch}',          104, 1, 'RESULT_BATCH',         'バッチテーブル（インポート/エクスポート専用）',               1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-task}',           105, 1, 'RESULT_TASK',          'タスクテーブル（インポート/エクスポート専用）',               1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-taskhst}',        106, 1, 'RESULT_TASK_HISTORY',  'タスク履歴テーブル（インポート/エクスポート専用）',           1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-device}',         107, 1, 'RESULT_DEVICE',        'デバイスマスタテーブル（インポート/エクスポート専用）',       1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-detail-device}',  108, 1, 'RESULT_DETAIL_DEVICE', 'デバイス明細マスタテーブル（インポート/エクスポート専用）',   1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-induction}',      109, 1, 'RESULT_INDUCTION',     'インダクションマスタテーブル（インポート/エクスポート専用）', 1, 0);
INSERT IGNORE INTO `mst_csv_type` (`csv_no`,`csv_order`,`heder_presence_flag`,`filename_prefix`,`type`,`delimiter`,`visible`) VALUES ('${ie-mapping-no.ie-sorting}',        110, 1, 'RESULT_SORTING',       '仕分けマスタテーブル（インポート/エクスポート専用）',         1, 0);
