-- [行追加]
-- 辞書データマスタ
-- 初期ディフォルト
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('work_instruction',            'workInstruction',          'radio',     1, '指示あり',         '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('work_instruction',            'workInstruction',          'radio',     2, '指示なし',         '0', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('work_type',                   'workType',                 'checkbox',  1, '単一',             '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('work_type',                   'workType',                 'checkbox',  3, '手仕分け',         '2', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('work_type',                   'workType',                 'checkbox',  2, 'まとめ',           '3', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('reject_setting',              'rejectSetting',            'radio',     1, 'リジェクトする',   '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('reject_setting',              'rejectSetting',            'radio',     2, 'リジェクトしない', '0', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('reject_show_error_flag',      'rejectShowErrorFlag',      'radio',     1, '表示',             '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('reject_show_error_flag',      'rejectShowErrorFlag',      'radio',     2, '非表示',           '0', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('scan_code',                   'scanCode',                 'radio',     1, '表示',             '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('scan_code',                   'scanCode',                 'radio',     2, '非表示',           '0', '0', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('link_number',                 'linkNumber',               'radio',     1, '表示',             '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('link_number',                 'linkNumber',               'radio',     2, '非表示',           '0', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('expiration_date',             'expirationDate',           'radio',     1, '表示',             '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('expiration_date',             'expirationDate',           'radio',      2, '非表示',          '0', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('manufacturing_lot',           'manufacturingLot',         'radio',     1, '表示',             '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('manufacturing_lot',           'manufacturingLot',         'radio',     2, '非表示',           '0', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('reserve',                     'reserve',                  'radio',     1, '表示',             '1', '1', NOW(), NOW());
INSERT IGNORE INTO `mst_dict_data` (`dict_type`, `field_id`, `html_type`, `dict_sort`, `dict_label`, `dict_value`, `is_visible`, `insert_time`, `update_time`) VALUES ('reserve',                     'reserve',                  'radio',     2, '非表示',           '0', '1', NOW(), NOW());
