-- タスクタイプ設定マスタ
-- [行追加]
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'taskTypeId',        1, 'タスクタイプ設定マスタ',               'タスクタイプID',            1, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'taskType',          2, 'タスクタイプ設定マスタ',               'タスクタイプ',              1, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'workInstruction',   3, 'タスクタイプ設定マスタ',               '作業指示',                 2, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'workType',          4, 'タスクタイプ設定マスタ',               '機能タイプ',                2, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'displaySort',       5, 'タスクタイプ設定マスタ',               '表示ソート',                1, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'displayFlag',       6, 'タスクタイプ設定マスタ',               '表示フラグ',                2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'lockGroup',         7, 'タスクタイプ設定マスタ',               'ロックグループ',             0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'reserveItem1',      8, 'タスクタイプ設定マスタ',               '予備項目1',                 0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'reserveItem2',      9, 'タスクタイプ設定マスタ',               '予備項目2',                 0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'reserveItem3',      10, 'タスクタイプ設定マスタ',              '予備項目3',                 0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'reserveItem4',      11, 'タスクタイプ設定マスタ',              '予備項目4',                 0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'reserveItem5',      12, 'タスクタイプ設定マスタ',              '予備項目5',                 0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'insertTime',        13, 'タスクタイプ設定マスタ',              '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskTypeSetting',       'updateTime',        14, 'タスクタイプ設定マスタ',              '更新日時',                  3, 1,0);

-- タスクタイプマスタ
-- [行追加]
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'taskTypeSerialId',       1, 'タスクタイプマスタ',               'シリアルID',                    1, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'taskType',               2, 'タスクタイプマスタ',               'タスクタイプ',                   1, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'taskTypeName',           3, 'タスクタイプマスタ',               'タスクタイプ名称',                0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'rejectSetting',          4, 'タスクタイプマスタ',               'リジェクト設定',                  2, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'rejectShowErrorFlag',    5, 'タスクタイプマスタ',               'リジェクトエラー表示フラグ',         2, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'rcsNo',                  6, 'タスクタイプマスタ',               'RCS番号',                       1, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'rcsName',                7, 'タスクタイプマスタ',               'RCS名',                         0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'reserveItem1',           8, 'タスクタイプマスタ',               '予備項目1',                      0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'reserveItem2',           9, 'タスクタイプマスタ',               '予備項目2',                      0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'reserveItem3',           10, 'タスクタイプマスタ',              '予備項目3',                      0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'reserveItem4',           11, 'タスクタイプマスタ',              '予備項目4',                      0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'reserveItem5',           12, 'タスクタイプマスタ',              '予備項目5',                      0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'insertTime',             13, 'タスクタイプマスタ',              '登録日時',                       3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstTaskType',       'updateTime',             14, 'タスクタイプマスタ',              '更新日時',                       3, 1,0);

