-- マッピング中間システム項目マスタ（インポート/エクスポート専用）
-- バッチ
INSERT IGNORE INTO `mst_mapping_is_item` (`mapping_no`,`line_num`,`is_item_no`,`is_item_name`,`serial_no`,`is_item_enabled_flag`) VALUES ('${ie-mapping-no.ie-batch}',3,'batchName','バッチ名',1,1);
UPDATE `mst_mapping_is_item` SET `line_num` = 4 WHERE `mapping_no` = '${ie-mapping-no.ie-batch}' AND `is_item_no` = 'taskType';
UPDATE `mst_mapping_is_item` SET `line_num` = 5 WHERE `mapping_no` = '${ie-mapping-no.ie-batch}' AND `is_item_no` = 'status';
UPDATE `mst_mapping_is_item` SET `line_num` = 6 WHERE `mapping_no` = '${ie-mapping-no.ie-batch}' AND `is_item_no` = 'temporaryHolding';
UPDATE `mst_mapping_is_item` SET `line_num` = 7 WHERE `mapping_no` = '${ie-mapping-no.ie-batch}' AND `is_item_no` = 'insertTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 8 WHERE `mapping_no` = '${ie-mapping-no.ie-batch}' AND `is_item_no` = 'updateTime';

-- タスク
INSERT IGNORE INTO `mst_mapping_is_item` (`mapping_no`,`line_num`,`is_item_no`,`is_item_name`,`serial_no`,`is_item_enabled_flag`) VALUES ('${ie-mapping-no.ie-task}',6,'batchName','バッチ名',1,1);
UPDATE `mst_mapping_is_item` SET `line_num` = 7 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'taskType';
UPDATE `mst_mapping_is_item` SET `line_num` = 8 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'status';
UPDATE `mst_mapping_is_item` SET `line_num` = 9 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'temporaryHolding';
UPDATE `mst_mapping_is_item` SET `line_num` = 10 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'shopNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 11 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'shopName';
UPDATE `mst_mapping_is_item` SET `line_num` = 12 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'productNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 13 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'scanCode';
UPDATE `mst_mapping_is_item` SET `line_num` = 14 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'scanMessage';
UPDATE `mst_mapping_is_item` SET `line_num` = 15 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'rfid';
UPDATE `mst_mapping_is_item` SET `line_num` = 16 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'manufacturingLot';
UPDATE `mst_mapping_is_item` SET `line_num` = 17 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'manufacturingExpirationDate';
UPDATE `mst_mapping_is_item` SET `line_num` = 18 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'orderUnit';
UPDATE `mst_mapping_is_item` SET `line_num` = 19 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'planQuantity';
UPDATE `mst_mapping_is_item` SET `line_num` = 20 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'resultQuantity';
UPDATE `mst_mapping_is_item` SET `line_num` = 21 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'csvOutFlag';
UPDATE `mst_mapping_is_item` SET `line_num` = 22 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'robotId';
UPDATE `mst_mapping_is_item` SET `line_num` = 23 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'taskOrder';
UPDATE `mst_mapping_is_item` SET `line_num` = 24 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'workType';
UPDATE `mst_mapping_is_item` SET `line_num` = 25 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'markWesNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 26 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'inductionId';
UPDATE `mst_mapping_is_item` SET `line_num` = 27 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'deviceId';
UPDATE `mst_mapping_is_item` SET `line_num` = 28 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'chuteNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 29 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'chuteBranchNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 30 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'scanTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 31 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'chuteTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 32 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'boxNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 33 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'changeNum';
UPDATE `mst_mapping_is_item` SET `line_num` = 34 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'remarks';
UPDATE `mst_mapping_is_item` SET `line_num` = 35 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'insertTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 36 WHERE `mapping_no` = '${ie-mapping-no.ie-task}' AND `is_item_no` = 'updateTime';

-- タスク履歴
INSERT IGNORE INTO `mst_mapping_is_item` (`mapping_no`,`line_num`,`is_item_no`,`is_item_name`,`serial_no`,`is_item_enabled_flag`) VALUES ('${ie-mapping-no.ie-taskhst}',6,'batchName','バッチ名',1,1);
UPDATE `mst_mapping_is_item` SET `line_num` = 7 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'taskType';
UPDATE `mst_mapping_is_item` SET `line_num` = 8 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'status';
UPDATE `mst_mapping_is_item` SET `line_num` = 9 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'temporaryHolding';
UPDATE `mst_mapping_is_item` SET `line_num` = 10 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'shopNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 11 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'shopName';
UPDATE `mst_mapping_is_item` SET `line_num` = 12 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'productNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 13 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'scanCode';
UPDATE `mst_mapping_is_item` SET `line_num` = 14 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'scanMessage';
UPDATE `mst_mapping_is_item` SET `line_num` = 15 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'rfid';
UPDATE `mst_mapping_is_item` SET `line_num` = 16 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'manufacturingLot';
UPDATE `mst_mapping_is_item` SET `line_num` = 17 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'manufacturingExpirationDate';
UPDATE `mst_mapping_is_item` SET `line_num` = 18 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'orderUnit';
UPDATE `mst_mapping_is_item` SET `line_num` = 19 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'planQuantity';
UPDATE `mst_mapping_is_item` SET `line_num` = 20 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'resultQuantity';
UPDATE `mst_mapping_is_item` SET `line_num` = 21 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'csvOutFlag';
UPDATE `mst_mapping_is_item` SET `line_num` = 22 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'robotId';
UPDATE `mst_mapping_is_item` SET `line_num` = 23 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'taskOrder';
UPDATE `mst_mapping_is_item` SET `line_num` = 24 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'workType';
UPDATE `mst_mapping_is_item` SET `line_num` = 25 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'markWesNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 26 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'inductionId';
UPDATE `mst_mapping_is_item` SET `line_num` = 27 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'deviceId';
UPDATE `mst_mapping_is_item` SET `line_num` = 28 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'chuteNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 29 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'chuteBranchNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 30 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'scanTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 31 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'chuteTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 32 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'boxNo';
UPDATE `mst_mapping_is_item` SET `line_num` = 33 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'changeNum';
UPDATE `mst_mapping_is_item` SET `line_num` = 34 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'remarks';
UPDATE `mst_mapping_is_item` SET `line_num` = 35 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'insertTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 36 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'updateTime';
UPDATE `mst_mapping_is_item` SET `line_num` = 37 WHERE `mapping_no` = '${ie-mapping-no.ie-taskhst}' AND `is_item_no` = 'histInsertTime';
