-- テーブル管理マスタ
-- AMR-ロケーションマスタ
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'locationSerialId',           1,'AMR-ロケーションマスタ',             'シリアルID',                1, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'locationNo',                 2,'AMR-ロケーションマスタ',             'ロケーション番号',          0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'locationType',               3,'AMR-ロケーションマスタ',             'ロケーションタイプ',        2, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'zoneNo',                     4,'AMR-ロケーションマスタ',             'ゾーン番号',                0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'amrFlag',                    5,'AMR-ロケーションマスタ',             'ＡＭＲ対象フラグ',          2, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'positionNo',                 6,'AMR-ロケーションマスタ',             'ポジション番号',            0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'insertTime',                 7,'AMR-ロケーションマスタ',             '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstLocation',        'updateTime',                 8,'AMR-ロケーションマスタ',             '更新日時',                  3, 1,0);
-- AMR-ポジションマスタ
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'positionSerialId',           1,'AMR-ポジションマスタ',               'シリアルID',                1, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'positionNo',                 2,'AMR-ポジションマスタ',               'ポジション番号',            0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'positionType',               3,'AMR-ポジションマスタ',               'ポジションタイプ',          2, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'areaNo',                      4,'AMR-ポジションマスタ',               'エリア番号',                  0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'positionLabel',              5,'AMR-ポジションマスタ',               'ポジションラベル',          0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'landMark',                   6,'AMR-ポジションマスタ',               'ランドマーク',              0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'actionType',                 7,'AMR-ポジションマスタ',               'アクションタイプ',          2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'coordinateXaxis',            8,'AMR-ポジションマスタ',               'X座標',                     1, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'coordinateYaxis',            9,'AMR-ポジションマスタ',               'Y座標',                     1, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'insertTime',                 10,'AMR-ポジションマスタ',               '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstPosition',        'updateTime',                 11,'AMR-ポジションマスタ',               '更新日時',                  3, 1,0);
-- AMR管理
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstAmr',             'amrSerialId',                 1,'AMR管理',                           'シリアルID',                1, 0,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstAmr',             'robotId',                     2,'AMR管理',                           'ロボットID',                0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstAmr',             'robotType',                   3,'AMR管理',                           'ロボットタイプ',          2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstAmr',             'robotStatus',                 4,'AMR管理',                           'ロボットステータス',        2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstAmr',             'funcType',                    5,'AMR管理',                           'ファンクションタイプ',      2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstAmr',             'insertTime',                  6,'AMR管理',                           '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstAmr',             'updateTime',                  7,'AMR管理',                           '更新日時',                  3, 1,0);
-- コンテナマスタ
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'containerSerialId',          1,'コンテナマスタ',                    'シリアルID',                1, 0,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'containerId',                2,'コンテナマスタ',                    'コンテナID',                0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'containerType',              3,'コンテナマスタ',                    'コンテナタイプ',            2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'length',                     4,'コンテナマスタ',                    '縦',                        1, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'width',                      5,'コンテナマスタ',                    '横',                        1, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'height',                     6,'コンテナマスタ',                    '高さ',                      1, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'insertTime',                 7,'コンテナマスタ',                    '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainer',        'updateTime',                 8,'コンテナマスタ',                    '更新日時',                  3, 1,0);
-- コンテナ配置マスタ
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainerPlacement',        'placementSerialId', 1,'コンテナ配置マスタ',                'シリアルID',                1, 0,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainerPlacement',        'placementNum',      2,'コンテナ配置マスタ',                '配置数',                    1, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainerPlacement',        'layoutPattern',     3,'コンテナ配置マスタ',                'パターン',                  1, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainerPlacement',        'patternName',       4,'コンテナ配置マスタ',                'パターン名',                  0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainerPlacement',        'layoutImgUrl',      5,'コンテナ配置マスタ',                'レイアウト図URL',           0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainerPlacement',        'insertTime',        6,'コンテナ配置マスタ',                '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstContainerPlacement',        'updateTime',        7,'コンテナ配置マスタ',                '更新日時',                  3, 1,0);
-- AMRタスク
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'amrTaskSerialId',            1,'AMRタスク',                           'シリアルID',                1, 0,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'amrTaskNo',                  2,'AMRタスク',                           'AMRタスク番号',              0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'amrTaskType',                3,'AMRタスク',                           'AMRタスクタイプ',            2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'routeId',                    4,'AMRタスク',                           'ルートID',                  0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'routeName',                  5,'AMRタスク',                           'ルート名',                  0, 0,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'robotId',                    6,'AMRタスク',                           'ロボットID',                0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'positionNo',                 7,'AMRタスク',                           '現在ポジション番号',          0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'routeNow',                   8,'AMRタスク',                           '現在ルート順番',             0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'amrStatus',                  9,'AMRタスク',                           'タスクステータス',            2, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'insertTime',                 10,'AMRタスク',                          '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('amrTask',             'updateTime',                 11,'AMRタスク',                          '更新日時',                  3, 1,0);
