-- テーブル管理マスタ
-- AMR-エリアマスタ
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstArea',             'areaSerialId',                 1,'AMR-エリアマスタ',                           'シリアルID',                1, 0,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstArea',             'areaNo',                     2,'AMR-エリアマスタ',                           'エリア番号',                0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstArea',             'areaName',                   3,'AMR-エリアマスタ',                           'エリア名',          0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstArea',             'coordinateXaxis',                 4,'AMR-エリアマスタ',                           'X座標',        0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstArea',             'coordinateYaxis',                    5,'AMR-エリアマスタ',                           'Y座標',      0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstArea',             'insertTime',                  6,'AMR-エリアマスタ',                           '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstArea',             'updateTime',                  7,'AMR-エリアマスタ',                           '更新日時',                  3, 1,0);

-- AMR-ゾーンマスタ
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'zoneSerialId',                 1,'AMR-ゾーンマスタ',                           'シリアルID',                1, 0,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'zoneNo',                     2,'AMR-ゾーンマスタ',                           'ゾーン番号',                0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'zoneName',                   3,'AMR-ゾーンマスタ',                           'ゾーン名',          0, 1,1);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'areaNo',                   4,'AMR-ゾーンマスタ',                           'エリア番号',          0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'coordinateXaxis',                 5,'AMR-ゾーンマスタ',                           'X座標',        0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'coordinateYaxis',                    6,'AMR-ゾーンマスタ',                           'Y座標',      0, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'insertTime',                  7,'AMR-ゾーンマスタ',                           '登録日時',                  3, 1,0);
INSERT IGNORE INTO `mst_table_management` (`table_no`,`is_item_no`,`item_order`,`table_name`,`item_name`,`data_type`,`display_flag`,`not_null_flag`) VALUES ('mstZone',             'updateTime',                  8,'AMR-ゾーンマスタ',                           '更新日時',                  3, 1,0);
